function exportcolors
    if test "$COLORSCHEME" = "sonokai"
        set -Ux color__bg "#181819"
        set -Ux color__fg "#E2E2E3"

        set -Ux color__black          "#222327"
        set -Ux color__red            "#FC5D7C"
        set -Ux color__green          "#9ED072"
        set -Ux color__yellow         "#E7C664"
        set -Ux color__blue           "#76CCE0"
        set -Ux color__pink           "#B39DF3"
        set -Ux color__purple         "#85D3F2"
        set -Ux color__gray_1         "#E2E2E3"
        set -Ux color__gray_2         "#595F67"
        set -Ux color__l_red          "#FC5D7C"
        set -Ux color__l_green        "#9ED072"
        set -Ux color__l_yellow       "#E7C664"
        set -Ux color__l_blue         "#76CCE0"
        set -Ux color__l_pink         "#B39DF3"
        set -Ux color__l_purple       "#85D3F2"
        set -Ux color__gray_3         "#E2E2E3"
        set -Ux color__transparent    "#181819CC"
        set -Ux color__white          "#F8F8F8"

    else if test "$COLORSCHEME" = "kanagawa"
        set color__bg "#16161D"
        set color__fg "#DCD7BA"

        set color__black          "#1F1F28"
        set color__red            "#E82424"
        set color__green          "#98BB6C"
        set color__yellow         "#FF9E3B"
        set color__blue           "#7E9CD8"
        set color__pink           "#957FB8"
        set color__purple         "#7AA89F"
        set color__gray_1         "#DCD7BA"
        set color__gray_2         "#54546D"
        set color__l_red          "#C34043" 
        set color__l_green        "#C8C093"
        set color__l_yellow       "#E7C664"
        set color__l_blue         "#7FB4CA"
        set color__l_pink         "#9CABCA"
        set color__l_purple       "#A3D4D5"
        set color__gray_3         "#DCD7BA"
        set color__transparent    "#16161DCC"
        set color__white          "#F8F8F8"

    else if test "$COLORSCHEME" = "panda"
        set color__bg "#292a2b"
        set color__fg "#E6E6E6"

        set color__black          "#292a2b"
        set color__red            "#FF2C6D"
        set color__green          "#19F9D8"
        set color__yellow         "#FFB86C"
        set color__blue           "#45A9FA"
        set color__pink           "#FF75B5"
        set color__purple         "#B084EB"
        set color__gray_1         "#757575"
        set color__gray_2         "#CDCDCD"
        set color__l_red          "#FF4B82"
        set color__l_green        "#6FE7D2"
        set color__l_yellow       "#FFCC95"
        set color__l_blue         "#6FC1FF"
        set color__l_pink         "#FF9AC1"
        set color__l_purple       "#BCAAFE"
        set color__gray_3         "#E6E6E6"
        set color__transparent    "#292a2bCC"
        set color__white          "#F8F8F8"
    end
end
